config/routes.rb
Rails.application.routes.draw do

  root 'searches#index'

  resources :searches

  resources :about

  resources :learn

  get'buildings/search' => 'buildings#search'
  post'buildings/search' => 'buildings#search'

  resources :buildings do
    member do
      get 'score'
      get 'complaint_count'
    end
    resources :ellis_acts
    resources :harassments
    resources :fix_orders
    resources :rent_notices
    resources :eviction_notices
  end
   resources :property_owners
   resources :tenants

end

app/models/building.rb
class Building < ActiveRecord::Base

  belongs_to :property_owner

  has_many  :tenants
  has_many  :ellis_acts

  has_many  :harassments
  has_many  :fix_orders
  has_many  :rent_notices
  has_many  :eviction_notices

  accepts_nested_attributes_for  :harassments
  accepts_nested_attributes_for  :fix_orders
  accepts_nested_attributes_for  :rent_notices
  accepts_nested_attributes_for  :eviction_notices


  #Data Import

  def self.import!
    new.import_pub!
  end

  def import_pub!
    # first_batch -- done
    # second_batch -- done
    # third_batch -- done
    # fourth_batch -- done
    # fifth_batch -- done
    # sixth_batch -- done
  end

  def first_batch
    import_ellis!("Ellis_Act_Withdrawals_1.csv")
  end

  def second_batch
    import_move_in!("Owner_Move_In.csv")
  end

  def third_batch
    import_move_in!("Owner_Move_In_2.csv")
  end

  def fourth_batch
    import_move_in!("Owner_Move_In_3.csv")
  end

  def fifth_batch
    import_move_in!("Owner_Move_In_4.csv")
    import_ellis!("Ellis_Act_Withdrawals_2.csv")
  end

  def sixth_batch
    import_condo!
  end

  def import_ellis!(file)
    CSV.foreach(file, encoding: "iso-8859-1:UTF-8", headers: true, header_converters: :symbol) do |row|
       @building = Building.where(orig_address: row[:address]).first
        next if row[:lat_long] == nil
       if exists?(row[:address])
         p "Changing ELLIS of #{row[:address]}"
         @building.ellis = true
       else
         latitude, longitude = parse_latitude_and_longitude_string(row[:lat_long])
          attributes = {
            address: reverse_geocode(latitude, longitude),
            zip_code: row[:zip_code],
            neighborhood: row[:neighborhood],
            orig_address: row[:address],
            latitude: latitude,
            longitude: longitude,
            ellis: true,
          }
          puts "Creating new building: #{attributes.inspect}"
          Building.create!(attributes)
       end
     end
   end

  def import_move_in!(file)
    CSV.foreach(file, encoding: "iso-8859-1:UTF-8", headers: true, header_converters: :symbol) do |row|
        @building = Building.where(orig_address: row[:address]).first
        next if row[:lat_long] == nil
        if exists?(row[:address])
          p "Changing move in of #{row[:address]}"
          @building.move_in = true
        else
          # p '*' * 80
          # p row.inspect
          # p '*' * 80

          latitude, longitude = parse_latitude_and_longitude_string(row[:lat_long])
          attributes = {
            address: reverse_geocode(latitude, longitude),
            zip_code: row[:zip_code],
            neighborhood: row[:neighborhood],
            latitude: latitude,
            orig_address: row[:address],
            longitude: longitude,
            move_in: true,
          }
          puts "Creating new building: #{attributes.inspect}"
          Building.create!(attributes)
        end
    end
  end

  def import_condo!
    CSV.foreach("Condo_Conv.csv", encoding: "iso-8859-1:UTF-8", headers: true, header_converters: :symbol) do |row|
        @building = Building.where(orig_address: row[:address]).first
          if exists?(row[:address])
          p "Changing condo conv of #{row[:address]}"
          @building.condo_conv = true
        else
          latitude, longitude = parse_latitude_and_longitude_string(row[:lat_long])
          attributes = {
            address: reverse_geocode(latitude, longitude),
            zip_code: row[:zip_code],
            neighborhood: row[:neighborhood],
            latitude: latitude,
            orig_address: row[:address],
            longitude: longitude,
            move_in: true,
          }
          puts "Creating new building: #{attributes.inspect}"
          Building.create!(attributes)
        end
    end
  end

  def reverse_geocode(lat,long)
    sleep(0.5)
    result = Geocoder.search("#{lat}, #{long}").first
    result.address.split(", ").first if result
  end

  def parse_latitude_and_longitude_string(string)
    string.gsub("(","").gsub(")","").split(", ")
  end

  def exists?(address)
    if Building.where(orig_address: address).first
      return true
    end
  end








  # search
  #reduces to numbers exlusively
  def only_numbers
    @address = self.address
    return @address.to_s.gsub(/\D/,"")
  end

  # algorithm
  def badge_score
    subtract_score.to_s.to_i
  end

  private

  def ellis_score
    if self.ellis_acts.all.length >= 1
      return 10
    else
      return 0
    end
  end

  def nofault_score
    if (self.move_in || self.condo_conv)
      return 5
    else
      return 0
    end
  end

  #~~~~~~~~~~~~~~~USER GENERATED~~~~~~~~~~~~~~~~~~~~~~

  #harassment

  def harass_score
    if self.harassments.all.length > 1
      return self.harassments.all.length**0.8
    elsif self.harassments.all.length == 1
      return 1
    else
      return 0
    end
  end


  #Maintenance Issue

  # def additional_unres_days
  #   self.days_unresolved - 7
  # end

  # def unres_days_score
  #   additional_unres_days**0.3
  # end

  # def day_score_calc
  #   if self.days_unresolved > 7
  #     return unres_days_score
  #   elsif self.days_unresolved >= 2
  #     return 1
  #   else
  #     return 0
  #   end
  # end

  def each_fix_total
    sum = 0
    self.fix_orders.all.each do |complaint|
      sum += complaint.day_score_calc
    end
    return sum
  end

  def num_fix_flags
    if self.fix_orders.all.length > 1
      return self.fix_orders.all.length**0.8
    else
      return 0
    end
  end

  def fix_score
    num_fix_flags + each_fix_total
  end

  #eviction complaint
  # def eviction_category_score
  #   if self.category == "Ellis Act"
  #     return 5
  #   elsif self.category == ("Landlord Move-In" || "Condo Coversion")
  #     return 3
  #   else
  #     return 0
  #   end
  # end

  def each_eviction_total
    sum = 0
    self.eviction_notices.all.each do |complaint|
      sum += complaint.eviction_category_score
    end
    return sum
  end

  def num_evict_flags
    if self.eviction_notices.all.length > 1
      return self.eviction_notices.all.length**1.5
    else
      return 0
    end
  end

  def eviction_score
    num_evict_flags + each_eviction_total
  end

  # rent increase

  # def percent_increase
  #   increase = (self.new_rent - self.prior_rent)/self.prior_rent
  #   if increase >= 0.1
  #     return increase
  #   else
  #     return 0
  #   end
  # end

  # def additional_increase
  #   add_inc = (percent_increase - 0.09)/0.05
  #   return (add_inc**0.3)
  # end

  def each_increase_total
    sum = 0
    self.rent_notices.all.each do |complaint|
      sum += (complaint.percent_increase + complaint.additional_increase)
    end
    return sum
  end

  def num_increase_flags
    if self.rent_notices.all.length > 1
      return self.rent_notices.all.length**1.5
    else
      return 0
    end
  end

  def rent_score
    num_increase_flags + each_increase_total
  end

  def user_score
    eviction_score + fix_score + harass_score + rent_score
  end

  def pub_score
    ellis_score + nofault_score
  end

  def weight_pub_score
    pub_score * 4
  end

  def total_score
    user_score + weight_pub_score
  end

  def subtract_score
    100 - total_score
  end

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  def new

    @report_categories = ["Select...", "LeaseIncrease", "MaintenenceIssue", "EvictionNotice", "OtherHarassment"]

    @letter_options = ["Ellis Act", "Landlord Move-In", "Condo Conversion"]

    session[:address] = params[:address]
    session[:zip_code] = params[:zipcode]

  end

  def create
    result = Geocoder.search(parse_address(session[:address],session[:zip_code])).first

    if result != nil
      @building = Building.new(
        address: format_address(result),
        zip_code: session[:zip_code],
        latitude: format_lat(result),
        longitude: format_long(result),
        neighborhood: format_neighborhood(result)
        )

      if @building.save

        @harassment = @building.harassments.build(category: params[:category],comment: params[:harasscomment])

        @fix_order = @building.fix_orders.build(days_unresolved: params[:days_unresolved],comment: params[:fixcomment], description: [:description])

        @rent_notice = @building.rent_notices.build(prior_rent: params[:prior_rent], new_rent: params[:new_rent], comment: params[:rentcomment])

        @eviction_notice = @building.eviction_notices.build(category: params[:eviccategory],comment: params[:eviccomment])

        if params[:harasscomment] != nil
          @harassment.save
        elsif params[:rentcomment] != nil
          @rent_notice.save
        elsif params[:fixcomment] != nil
          @fix_order.save
        elsif params[:eviccomment] != nil
          @eviction_notice.save
        end



        redirect_to @building

       else
         render json: @building.errors.to_json
       end
     end

  end

  def show

    @report_categories = ["Select...", "LeaseIncrease", "MaintenenceIssue", "EvictionNotice", "OtherHarassment"]

    @letter_options = ["Ellis Act", "Landlord Move-In", "Condo Conversion"]

    @building = Building.where(id: params[:id]).first

#begin variables to send info to the map
    @latitude = @building.latitude
    @longitude = @building.longitude
    @address = @building.address
    @neighborhood = @building.neighborhood
# end variables to send info to the map

    @reports_array = []
    @building.harassments.each do |report|
      @reports_array << report
    end

    @building.fix_orders.each do |report|
      @reports_array << report
    end

    @building.eviction_notices.each do |report|
      @reports_array << report
    end

    @building.rent_notices.each do |report|
      @reports_array << report
    end

    @reports_array.sort!{|a,b|b.updated_at <=> a.updated_at}

    @reports_array = @reports_array.first(10)

    render :"buildings/building_profile"
    # render json:  @search
    end

    def score
      @building = Building.find(params[:id])
      response = {:score => @building.badge_score}
      render json: response.to_json

    end

    def complaint_count
      @building = Building.find(params[:id])
      response = {:harass => @building.harassments.count, :fix_order => @building.fix_orders.count, :evic => @building.eviction_notices.count, :rent => @building.rent_notices.count}
      render json: response.to_json
    end

    private

    def parse_address(address,zip_code)
      address + ", " + zip_code.to_s
    end

    def format_address(data)
      data.address_components[0]["long_name"] + " " + data.address_components[1]["long_name"]
    end

    def format_lat(data)
      data.geometry["location"]["lat"]
    end

    def format_long(data)
      data.geometry["location"]["lng"]
    end

    def format_neighborhood(data)
      data.address_components[2]["long_name"]
    end

end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_building_map.html.erb
    <script>
/*
 * This demo illustrates the coordinate system used to display map tiles in the
 * API.
 *
 * Tiles in Google Maps are numbered from the same origin as that for
 * pixels. For Google's implementation of the Mercator projection, the origin
 * tile is always at the northwest corner of the map, with x values increasing
 * from west to east and y values increasing from north to south.
 *
 * Try panning and zooming the map to see how the coordinates change.
 */

/** @constructor */


function CoordMapType(tileSize) {
  this.tileSize = tileSize;
}

CoordMapType.prototype.getTile = function(coord, zoom, ownerDocument) {
  var div = ownerDocument.createElement('div');
  div.innerHTML = coord;
  div.style.width = this.tileSize.width + 'px';
  div.style.height = this.tileSize.height + 'px';
  div.style.fontSize = '10';
  div.style.borderStyle = 'solid';
  div.style.borderWidth = '1px';
  div.style.borderColor = '#AAAAAA';
  return div;
};

var map;

var latitude = '<%= @latitude %>';
var longitude = '<%= @longitude %>';
var address = '<%= @address %>';
var neighborhood = '<%= @neighborhood %>';

var currentBuilding = new google.maps.LatLng(latitude, longitude);

function initialize() {
  var mapOptions = {
    zoom: 18,
    center: currentBuilding,
    // mapTypeId: google.maps.MapTypeId.SATELLITE,
  };

  map = new google.maps.Map(document.getElementById('map-canvas'),
                                    mapOptions);

  // Insert this overlay map type as the first overlay map type at
  // position 0. Note that all overlay map types appear on top of
  // their parent base map.
  map.overlayMapTypes.insertAt(
      0, new CoordMapType(new google.maps.Size(256, 256)));
  buildingInfo = '<h3>'+ address +'</h3>' +
  '<p>Neighborhood: '+ neighborhood+'</p>'

  var infowindow = new google.maps.InfoWindow({
      content: buildingInfo
  });

  var marker = new google.maps.Marker({
      position: currentBuilding,
      map: map,
      title: address
  });
  google.maps.event.addListener(marker, 'click', function() {
    infowindow.open(map,marker);
  });
}

// google.maps.event.addDomListener(document.getElementById('map-canvas'), 'load', initialize);

    </script>

app/views/buildings/building_profile.html.erb
<body data-no-turbolink="true">
<div class="container debug">
  <!-- Top row -->
  <div class="row top-row debug">
<!-- Quadrant 1 -->
    <div class="col-xs-12 col-md-6 debug">


        <div class="score-box">
          <span class="badge" id="score-badge"><%=@building.badge_score%></span>
        </div>
        <h1 class="address"><%= @building.address %></h1>

      <div class="building-summary">
        <h2>What You Need to Know</h2>
          <div class="eviction-summary">
            <%if @building.ellis%>
              <p>Tenants were evicted at this building under the Ellis Act.</p>
            <%elsif @building.move_in%>
              <p>Tenants were evicted at this building because the owner or his or her close relative moved in.</p>
            <%elsif @building.condo_conv%>
              <p>Tenants were evicted at this building because the building was converted into condos.</p>
            <%end%>
          </div>

          <ul>
            <li>Harassment Complaints: <span id="harass-count"><%=@building.harassments.count %></span></li>
            <li>Maintenence Issues: <span id="fix-count"><%=@building.fix_orders.count %></span></li>
            <li>Eviction Notices: <span id="evic-count"><%=@building.eviction_notices.count %></span></li>
            <li>Rent Increases: <span id="rent-count"><%=@building.rent_notices.count %></span></li>
          </ul>
      </div>

    </div>

    <!-- end Quadrant 1 -->

    <!-- Quadrant 2 -->


    <div class="col-xs-12 col-md-6 debug">
      <div id="map-canvas"></div>
    </div>

    <!-- End quadrant 2 -->
  </div>
  <!-- End of top row -->
  <!-- beginning of second row -->
  <div class="row prof-row debug" id="report-row">

    <!-- Quadrant 4 -->

    <div class="col-xs-12 col-md-6 debug">
          <div class="recent-reports-comments">
          <div class="well">

                  <h4 class="type-of-comment"></h4><br>

                <span class="created"></span> | Comment: <span class="report_comment"></span>
          </div>
          <% if @reports_array.length > 0 %>
          <h2>Recent Reports</h2>
            <% @reports_array.each do |report| %>
              <div class="well">
                <% if report.class.to_s == "EvictionNotice"  %>
                  <h4 class="type-of-comment">Eviction Notice</h4><br>
                <% elsif  report.class.to_s == "FixOrder" %>
                  <h4 class="type-of-comment">Maintenance Issue</h4><br>
                <% elsif  report.class.to_s == "RentNotice"  %>
                  <h4 class="type-of-comment">Rent Increase</h4><br>
                <% elsif  report.class.to_s == "Harassment"  %>
                  <h4 class="type-of-comment">Landlord Harassment</h4><br>
                <% end %>
                <span class="created"><%= report.created_at.strftime("%b %d, %Y") %></span> | Comment: <span class="report_comment"><%= report.comment %></span>
              </div>
            <% end %>
          <% end %>
        </div>
        </div>
    <!-- End Quadrant 4 -->

    <!-- Quadrant 3 -->
    <div class="col-xs-12 col-md-6 debug report-button-container">
      <button class="btn" id="report-button">Report On Your Building</button>
    </div>
    <!-- End Quadrant 3 -->


  </div>
  <!-- End of second row -->
  <!-- start of third row -->
  <div class="row debug">
    <div class="report-container">

      <div class="form-contents">
        <div role="tabpanel">

          <!-- Nav tabs -->
          <ul class="nav nav-tabs report-toggle" role="tablist">
            <li role="presentation" class="active"><a href="#lease-increase" aria-controls="lease-increase" role="tab" data-toggle="tab">Lease Increase</a></li>
            <li role="presentation"><a href="#maint-issue" aria-controls="maint-issue" role="tab" data-toggle="tab">Maintenance</a></li>
            <li role="presentation"><a href="#evic-notices" aria-controls="evic-notices" role="tab" data-toggle="tab">Eviction Notices</a></li>
            <li role="presentation"><a href="#harassment" aria-controls="harassment" role="tab" data-toggle="tab">Harassment</a></li>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="lease-increase"><%= render partial: 'reports/leaseincrease' %></div>
            <div role="tabpanel" class="tab-pane" id="maint-issue"><%= render partial: 'reports/maintenenceissue' %></div>
            <div role="tabpanel" class="tab-pane" id="evic-notices"><%= render partial: 'reports/evictionnotice' %></div>
            <div role="tabpanel" class="tab-pane" id="harassment"><%= render partial: 'reports/otherharassment' %></div>
          </div>




    </div>

  </div>
  <!-- end of third row -->
</div>
<!-- End containter -->

    <%= render partial: 'buildings/building_map' %>













    </div>
  </body>

app/views/buildings/index.html.erb
<div class="home-container debugger ">

  <!-- <div class="hero-image debugger">
  </div> -->

  <div class="search-and-report-container abode-well-hero-container abode-well-hero-background">

  </div>
  <div class="abode-well-hero-form">
    <div class="search-errors">
    </div>
    <form class="form-inline search-form" action="/searches/" method="post">
      <div class="form-group">
        <label for="search-address">Address</label>
        <input type="text" class="form-control" name="address" id="search-address">
      </div>
      <div class="form-group">
        <label for="search-zip-code">Zip Code</label>
        <input type="text" class="form-control" name="zip_code" id="search-zip-code">
      </div>
      <button type="submit" class="btn btn-default">Search Properties</button>
    </form>

  </div>

<%= render "about/about" %>

</div>



  <!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" id="modal-x-btn" data-dismiss="modal">&times;</button>
        <h1 class="results_title"> Is this the address you meant? </h1>
      </div>
      <div class="modal-body">

          <div class="results-modal">

          </div>

       </div>
      </div>
      <div class="modal-footer">
        <button type="button" id="modal-fail-btn" class="btn btn-default">Not Seeing Your Building?</button>
      </div>
    </div>

  </div>
</div>


















</div> <!-- home-container end -->

app/views/buildings/new.html.erb
<div class="container debug">
  <!-- Top Row -->
  <div class="row top-row debug">
    <div class="jumbotron">
      <h1>No News is Good News</h1>
      <h2>Here's what we know about this building:</h2>
      <p>
        No one has been displaced from this building due to Ellis Act evictions, condo conversion evictions, or owner move-in evictions.
      </p>
        <div class="pine-nuts">
        <a class="btn btn-primary btn-lg action-btns" href="/about" role="button">Learn more</a>
        <a class="btn btn-primary btn-lg action-btns" id="new-build-rprt" href="#" role="button">File a New Report</a>
      </div>
    </div>
  </div>
  <!-- End of top row -->
  <!-- Start of Second row -->
  <div class="row debug">
    <div class="report-container debug">

      <div class="form-contents debug">
        <div role="tabpanel">

          <!-- Nav tabs -->
          <ul class="nav nav-tabs report-toggle" role="tablist">
            <li role="presentation" class="active"><a href="#lease-increase" aria-controls="lease-increase" role="tab" data-toggle="tab">Lease Increase</a></li>
            <li role="presentation"><a href="#maint-issue" aria-controls="maint-issue" role="tab" data-toggle="tab">Maintenance</a></li>
            <li role="presentation"><a href="#evic-notices" aria-controls="evic-notices" role="tab" data-toggle="tab">Eviction Notices</a></li>
            <li role="presentation"><a href="#harassment" aria-controls="harassment" role="tab" data-toggle="tab">Harassment</a></li>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="lease-increase"><%= render partial: 'new_reports/leaseincrease' %></div>
            <div role="tabpanel" class="tab-pane" id="maint-issue"><%= render partial: 'new_reports/maintenenceissue' %></div>
            <div role="tabpanel" class="tab-pane" id="evic-notices"><%= render partial: 'new_reports/evictionnotice' %></div>
            <div role="tabpanel" class="tab-pane" id="harassment"><%= render partial: 'new_reports/otherharassment' %></div>
          </div>




    </div>

  </div>
  <!-- End of Second row -->
</div>

app/views/buildings/results.html.erb
<div class="results-page ghost-image">
	<div class="results_matching">
		<h1 class="results_title">	Matching Addresses </h1>
		<table class="results_table">
		  <tr>
		    <th>Address:</th>
		    <th class="results-middle">Zip:</th>
		    <th class="results-middle">Neighborhood:</th>
		  </tr>
			<%@only_zips.each do |building| %>
			  <tr>
				  <!-- @address= building.zip_code -->
				  <td><%=link_to building.address, building_path(building) %></td>
			    <td class="results-middle"><%=building.zip_code%></td>
			    <td class="results-middle"><%=building.neighborhood%></td>
			  </tr>
			<% end %>
		</table>
	</div>

	<div class="results_matching">
		<h1 class="results_title">	More homes in this neighborhood </h1>
		<table class="results_table">
		  <tr>
		    <th>Address:</th>
		    <th class="results-middle">Zip:</th>
		    <th class="results-middle">Neighborhood:</th>
		  </tr>
		  <!-- grab the a set number of examples -->
			<%@new =@neighbors.sample(10)  %>


			<%@new.each do |building| %>
			  <tr>
			  <!-- @address= building.zip_code -->
				  <td><%=link_to building.address, building_path(building) %></td>
			    <td class="results-middle"><%=building.zip_code%></td>
			    <td class="results-middle"><%=building.neighborhood%></td>
			  </tr>
			<% end %>
		</table>
	</div>

</div>

app/views/buildings/search.html.erb
<h1> for the love of buddah, please start working </h1>